name: Tests

on:
  push:
    branches: ["main", "develop", "j2"]
  pull_request:
    branches: ["main"]

jobs:
  unitaires:
    name: tests unitaires du jeu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Installation des dependances
        run: npm ci

      - name: Execution des tests
        run: npm test
